#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=4,walltime=5:00:00

## modules
echo "Loading modules"
module unload matlab
module load matlab/2017a
module unload python
module load dipy/dev

echo "Check the inputs subject id"
afq_sub1_id=`jq -r '._inputs[0].meta.subject' config.json`
t1_sub1_id=`jq -r '._inputs[1].meta.subject' config.json`
afq_sub2_id=`jq -r '._inputs[2].meta.subject' config.json`
t1_sub2_id=`jq -r '._inputs[3].meta.subject' config.json`
run=`jq -r '.run' config.json`
if [ $afq_sub1_id == $t1_sub1_id -a $afq_sub2_id == $t1_sub2_id ]; then
	echo "Inputs subject IDs correctly inserted"
else
	echo "Inputs subject IDs incorrectly inserted. Check them again."
	exit 1
fi
segmentation1=`jq -r '.segmentation1' config.json`
segmentation2=`jq -r '.segmentation2' config.json`
if [ $segmentation1 == $segmentation2 ]; then
	echo "Error: estimated segmentation and ground truth segmentation are the same. DSC will be 1."
	exit 1
fi

echo "AFQ conversion to trk"
matlab -nosplash -nodisplay -r "afqConverter2()";

ret=$?
if [ ! $ret -eq 0 ]; then
	echo "AFQ conversion failed"
	echo $ret > finished
	exit $ret
fi

echo "Computing voxel measures"
python compute_dsc4hcp.py -sub $afq_sub1_id -list 'tract_name_list.txt' -run $run;

ret=$?
if [ ! $ret -eq 0 ]; then
	echo "DSC computation failed"
	echo $ret > finished
	exit $ret
fi

echo "Complete"
